### ISSUE TITLE
new update

### ISSUE THREAD

**Issue by poorloading** [DeathMiner/RewardsGG-Farm#5] opened 2016-03-15 00:27 UTC
im not rushing the maker of this script but is there any eta at all on the update ? i was also wondering if there is anyway to know how many tickets you need to take every spot on a item.

**Comment by demaisj** [comment] 2016-03-15 07:10
Hello,

I'm kind of busy right now (school stuff you know), but I'm doing my best to find some time to code the big update.
If someone got some time to spend I'm accepting pull requests too!

I hope you've understood why the update is delayed.

**Comment by poorloading** [comment] 2016-03-15 08:06
yes i under stand, and i hope you dont think i was rushing .hope you know people love your script =p

**Comment by demaisj** [comment] 2016-03-15 08:15
No problem ;)
I know the script is broken and I have to fix it asap. It's annoying for the users and even myself.

Anyway thanks for the support, it's always nice to see people appreciating my work.

**Comment by divit0n** [comment] 2016-03-16 19:02
thanks for great script im waiting for update too :)
i found 2 new sites:
http://www.winaskin.com/earn.html
http://get-skins.net/earngs

**Comment by demaisj** [comment] 2016-03-16 19:58
Thank you,
maybe i'll do a script for these websites too, if I find the time to do it, and if I find the breaches.
Also, I'll try to update the rewards.gg script this week.

**Comment by divit0n** [comment] 2016-03-16 21:30
cool thanks

**Comment by demaisj** [comment] 2016-03-18 23:40
Hello, there is some news about the upcoming update there: https://github.com/DeathMiner/RewardsGG-Farm/issues/4#issuecomment-198584804

**Comment by demaisj** [comment] 2016-03-25 20:40
I'm closing this issue for now, this is a duplicate of issue #4.

**Closed as completed by demaisj** 2016-03-25 20:40 UTC
Labels: duplicate
